// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiyb8MKslDI24yi5jLRduPsx471g0jPyk',
    appId: '1:574001282363:web:76f2f661586493f2620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    authDomain: 'margdarshak-345f4.firebaseapp.com',
    storageBucket: 'margdarshak-345f4.appspot.com',
    measurementId: 'G-WXGJG9T4LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGMKun73sy1phMjiPe8fVdoEBmF9xvWE',
    appId: '1:574001282363:android:e9ba4197313a5f76620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    storageBucket: 'margdarshak-345f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoAhmHTS9WGr_X6oPEbe4onWgkDPTcTgA',
    appId: '1:574001282363:ios:06f0e78b4cda9d6a620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    storageBucket: 'margdarshak-345f4.appspot.com',
    iosBundleId: 'com.example.copyOfMargdrashak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoAhmHTS9WGr_X6oPEbe4onWgkDPTcTgA',
    appId: '1:574001282363:ios:06f0e78b4cda9d6a620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    storageBucket: 'margdarshak-345f4.appspot.com',
    iosBundleId: 'com.example.copyOfMargdrashak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiyb8MKslDI24yi5jLRduPsx471g0jPyk',
    appId: '1:574001282363:web:5d33dabc8d1a0fc0620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    authDomain: 'margdarshak-345f4.firebaseapp.com',
    storageBucket: 'margdarshak-345f4.appspot.com',
    measurementId: 'G-9TJMW367Q0',
  );
}
